-- claude.nvim — a Neovim colorscheme that mirrors the Claude Code CLI.
--
-- The palette is lifted verbatim from the Claude Code v2.1.143 binary's
-- theme tables: coral #d77757 is the one brand accent, and the supporting
-- tones (periwinkle, teal, amber, green, purple) are Claude Code's own
-- status, permission, and diff colors. lua/appearance.lua flips
-- vim.o.background from the terminal's OSC 11 reply, which selects the
-- light or dark palette below.

vim.cmd.highlight("clear")
if vim.g.syntax_on then
    vim.cmd.syntax("reset")
end
vim.g.colors_name = "claude"

local dark = {
    bg         = "#1a1a1a",
    fg         = "#ffffff",
    fg_dim     = "#999999",
    fg_subtle  = "#505050",
    punct      = "#888888",
    cursorline = "#262626",
    surface    = "#242424",
    surface_hi = "#242424",
    indent     = "#2c2c2c",
    sel        = "#313140",
    sel_menu   = "#3a3c52",
    match      = "#45484f",
    coral      = "#d77757",
    coral_lt   = "#eb9f7f",
    peri       = "#b1b9f9",
    green      = "#4eba65",
    amber      = "#ffc107",
    teal       = "#48968c",
    purple     = "#af87ff",
    pink       = "#fd5db1",
    red        = "#ff6b80",
    inverse    = "#1a1a1a",
    search     = "#5a3a2c",
    search_cur = "#d77757",
    diff_add   = "#225c2b",
    diff_del   = "#7a2936",
    diff_chg   = "#2f3328",
    diff_txt   = "#3c5a30",
    git_add    = "#38a660",
    git_chg    = "#ffc107",
    git_del    = "#b3596b",
}

local light = {
    bg         = "#fafafa",
    fg         = "#000000",
    fg_dim     = "#666666",
    fg_subtle  = "#afafaf",
    punct      = "#888888",
    cursorline = "#ededed",
    surface    = "#ececec",
    surface_hi = "#f4f4f4",
    indent     = "#e4e4e4",
    sel        = "#dde0f7",
    sel_menu   = "#d4d9f7",
    match      = "#d0d0d0",
    coral      = "#d77757",
    coral_lt   = "#c25f3d",
    peri       = "#5769f7",
    green      = "#2c7a39",
    amber      = "#966c1e",
    teal       = "#006666",
    purple     = "#8700ff",
    pink       = "#c0398a",
    red        = "#ab2b3f",
    inverse    = "#ffffff",
    search     = "#f0d9cc",
    search_cur = "#d77757",
    diff_add   = "#c7e1cb",
    diff_del   = "#fdd2d8",
    diff_chg   = "#ece3cf",
    diff_txt   = "#a8d4ae",
    git_add    = "#2f9d44",
    git_chg    = "#966c1e",
    git_del    = "#d1454b",
}

local p = vim.o.background == "light" and light or dark
local NONE = "NONE"

local groups = {
    -- Editor UI
    Normal       = { fg = p.fg, bg = p.bg },
    NormalNC     = { fg = p.fg, bg = p.bg },
    NormalFloat  = { fg = p.fg, bg = p.surface_hi },
    FloatBorder  = { fg = p.peri, bg = p.surface_hi },
    FloatTitle   = { fg = p.coral, bg = p.surface_hi, bold = true },
    FloatFooter  = { fg = p.fg_dim, bg = p.surface_hi },
    ColorColumn  = { bg = p.cursorline },
    Cursor       = { fg = p.inverse, bg = p.coral },
    lCursor      = { fg = p.inverse, bg = p.coral },
    TermCursor   = { fg = p.inverse, bg = p.coral },
    CursorLine   = { bg = p.cursorline },
    CursorColumn = { bg = p.cursorline },
    CursorLineNr = { fg = p.coral, bold = true },
    LineNr       = { fg = p.fg_subtle },
    LineNrAbove  = { link = "LineNr" },
    LineNrBelow  = { link = "LineNr" },
    SignColumn   = { bg = NONE },
    FoldColumn   = { fg = p.fg_subtle, bg = NONE },
    Folded       = { fg = p.fg_dim, bg = p.cursorline },
    WinSeparator = { fg = p.surface },
    VertSplit    = { fg = p.surface },
    NonText      = { fg = p.fg_subtle },
    Whitespace   = { fg = p.fg_subtle },
    SpecialKey   = { fg = p.fg_subtle },
    EndOfBuffer  = { fg = p.fg_subtle },
    Visual       = { bg = p.sel },
    VisualNOS    = { bg = p.sel },
    Search       = { fg = p.fg, bg = p.search },
    IncSearch    = { fg = p.inverse, bg = p.search_cur },
    CurSearch    = { fg = p.inverse, bg = p.search_cur },
    Substitute   = { fg = p.inverse, bg = p.search_cur },
    MatchParen   = { bg = p.match, bold = true },
    Pmenu        = { fg = p.fg, bg = p.surface },
    PmenuSel     = { fg = p.fg, bg = p.sel_menu, bold = true },
    PmenuSbar    = { bg = p.surface },
    PmenuThumb   = { bg = p.fg_subtle },
    PmenuKind    = { fg = p.peri, bg = p.surface },
    PmenuExtra   = { fg = p.fg_dim, bg = p.surface },
    WildMenu     = { link = "PmenuSel" },
    StatusLine   = { fg = p.fg_dim, bg = p.surface },
    StatusLineNC = { fg = p.fg_subtle, bg = p.surface },
    TabLine      = { fg = p.fg_dim, bg = p.surface },
    TabLineSel   = { fg = p.coral, bg = NONE, bold = true },
    TabLineFill  = { bg = NONE },
    WinBar       = { fg = p.fg_dim, bg = NONE },
    WinBarNC     = { fg = p.fg_subtle, bg = NONE },
    Title        = { fg = p.coral, bold = true },
    Directory    = { fg = p.peri },
    ErrorMsg     = { fg = p.red },
    WarningMsg   = { fg = p.amber },
    ModeMsg      = { fg = p.fg_dim },
    MoreMsg      = { fg = p.green },
    Question     = { fg = p.green },
    MsgArea      = { fg = p.fg },
    MsgSeparator = { fg = p.surface },
    QuickFixLine = { bg = p.sel },
    qfFileName   = { fg = p.peri },
    qfLineNr     = { fg = p.fg_dim },
    Conceal      = { fg = p.fg_dim },
    SpellBad     = { undercurl = true, sp = p.red },
    SpellCap     = { undercurl = true, sp = p.amber },
    SpellRare    = { undercurl = true, sp = p.purple },
    SpellLocal   = { undercurl = true, sp = p.teal },
    DiffAdd      = { bg = p.diff_add },
    DiffDelete   = { fg = p.fg_dim, bg = p.diff_del },
    DiffChange   = { bg = p.diff_chg },
    DiffText     = { bg = p.diff_txt },

    -- Standard syntax
    Comment        = { fg = p.fg_dim },
    Constant       = { fg = p.amber },
    String         = { fg = p.green },
    Character      = { fg = p.green },
    Number         = { fg = p.amber },
    Boolean        = { fg = p.amber },
    Float          = { fg = p.amber },
    Identifier     = { fg = p.fg },
    Function       = { fg = p.peri },
    Statement      = { fg = p.coral },
    Conditional    = { fg = p.coral },
    Repeat         = { fg = p.coral },
    Label          = { fg = p.coral },
    Operator       = { fg = p.punct },
    Keyword        = { fg = p.coral },
    Exception      = { fg = p.coral },
    PreProc        = { fg = p.purple },
    Include        = { fg = p.purple },
    Define         = { fg = p.purple },
    Macro          = { fg = p.purple },
    PreCondit      = { fg = p.purple },
    Type           = { fg = p.teal },
    StorageClass   = { fg = p.teal },
    Structure      = { fg = p.teal },
    Typedef        = { fg = p.teal },
    Special        = { fg = p.coral_lt },
    SpecialChar    = { fg = p.coral_lt },
    Tag            = { fg = p.coral },
    Delimiter      = { fg = p.punct },
    SpecialComment = { fg = p.fg_dim, bold = true },
    Debug          = { fg = p.red },
    Underlined     = { underline = true },
    Ignore         = { fg = p.fg_subtle },
    Error          = { fg = p.red },
    Todo           = { fg = p.inverse, bg = p.amber, bold = true },
    Added          = { fg = p.git_add },
    Removed        = { fg = p.git_del },
    Changed        = { fg = p.git_chg },

    -- Treesitter
    ["@variable"]              = { fg = p.fg },
    ["@variable.builtin"]      = { fg = p.coral },
    ["@variable.parameter"]    = { fg = p.fg },
    ["@variable.member"]       = { fg = p.fg },
    ["@property"]              = { fg = p.fg },
    ["@field"]                 = { fg = p.fg },
    ["@module"]                = { fg = p.fg },
    ["@constant"]              = { fg = p.amber },
    ["@constant.builtin"]      = { fg = p.purple },
    ["@constant.macro"]        = { fg = p.purple },
    ["@string"]                = { link = "String" },
    ["@string.escape"]         = { fg = p.coral_lt },
    ["@string.special"]        = { fg = p.coral_lt },
    ["@string.regexp"]         = { fg = p.coral_lt },
    ["@character"]             = { link = "Character" },
    ["@number"]                = { link = "Number" },
    ["@number.float"]          = { link = "Float" },
    ["@boolean"]               = { link = "Boolean" },
    ["@function"]              = { fg = p.peri },
    ["@function.builtin"]      = { fg = p.peri },
    ["@function.call"]         = { fg = p.peri },
    ["@function.macro"]        = { fg = p.purple },
    ["@function.method"]       = { fg = p.peri },
    ["@function.method.call"]  = { fg = p.peri },
    ["@constructor"]           = { fg = p.teal },
    ["@keyword"]               = { fg = p.coral },
    ["@keyword.function"]      = { fg = p.coral },
    ["@keyword.operator"]      = { fg = p.coral },
    ["@keyword.return"]        = { fg = p.coral },
    ["@keyword.conditional"]   = { fg = p.coral },
    ["@keyword.repeat"]        = { fg = p.coral },
    ["@keyword.exception"]     = { fg = p.coral },
    ["@keyword.import"]        = { fg = p.purple },
    ["@keyword.directive"]     = { fg = p.purple },
    ["@operator"]              = { fg = p.punct },
    ["@punctuation.delimiter"] = { fg = p.punct },
    ["@punctuation.bracket"]   = { fg = p.punct },
    ["@punctuation.special"]   = { fg = p.coral },
    ["@comment"]               = { link = "Comment" },
    ["@comment.todo"]          = { fg = p.inverse, bg = p.amber, bold = true },
    ["@comment.error"]         = { fg = p.inverse, bg = p.red, bold = true },
    ["@comment.warning"]       = { fg = p.inverse, bg = p.amber, bold = true },
    ["@comment.note"]          = { fg = p.inverse, bg = p.peri, bold = true },
    ["@type"]                  = { fg = p.teal },
    ["@type.builtin"]          = { fg = p.teal },
    ["@type.definition"]       = { fg = p.teal },
    ["@attribute"]             = { fg = p.purple },
    ["@label"]                 = { fg = p.coral },
    ["@tag"]                   = { fg = p.coral },
    ["@tag.attribute"]         = { fg = p.peri },
    ["@tag.delimiter"]         = { fg = p.punct },
    ["@markup.heading"]        = { fg = p.coral, bold = true },
    ["@markup.strong"]         = { bold = true },
    ["@markup.italic"]         = { italic = true },
    ["@markup.strikethrough"]  = { strikethrough = true },
    ["@markup.link"]           = { fg = p.peri },
    ["@markup.link.label"]     = { fg = p.peri },
    ["@markup.link.url"]       = { fg = p.teal, underline = true },
    ["@markup.raw"]            = { fg = p.green },
    ["@markup.list"]           = { fg = p.coral },
    ["@markup.quote"]          = { fg = p.fg_dim },
    ["@diff.plus"]             = { fg = p.git_add },
    ["@diff.minus"]            = { fg = p.git_del },
    ["@diff.delta"]            = { fg = p.git_chg },
    ["@lsp.type.comment"]      = {},

    -- Diagnostics
    DiagnosticError            = { fg = p.red },
    DiagnosticWarn             = { fg = p.amber },
    DiagnosticInfo             = { fg = p.peri },
    DiagnosticHint             = { fg = p.teal },
    DiagnosticOk               = { fg = p.green },
    DiagnosticVirtualTextError = { fg = p.red },
    DiagnosticVirtualTextWarn  = { fg = p.amber },
    DiagnosticVirtualTextInfo  = { fg = p.peri },
    DiagnosticVirtualTextHint  = { fg = p.teal },
    DiagnosticVirtualTextOk    = { fg = p.green },
    DiagnosticUnderlineError   = { undercurl = true, sp = p.red },
    DiagnosticUnderlineWarn    = { undercurl = true, sp = p.amber },
    DiagnosticUnderlineInfo    = { undercurl = true, sp = p.peri },
    DiagnosticUnderlineHint    = { undercurl = true, sp = p.teal },
    DiagnosticUnderlineOk      = { undercurl = true, sp = p.green },
    DiagnosticDeprecated       = { strikethrough = true, sp = p.fg_dim },
    DiagnosticUnnecessary      = { fg = p.fg_dim },

    -- LSP
    LspReferenceText           = { bg = p.match },
    LspReferenceRead           = { bg = p.match },
    LspReferenceWrite          = { bg = p.match },
    LspSignatureActiveParameter = { fg = p.coral, bold = true },
    LspInlayHint               = { fg = p.fg_subtle },
    LspCodeLens                = { fg = p.fg_dim },
    LspInfoBorder              = { link = "FloatBorder" },

    -- Git / diff text
    diffAdded     = { fg = p.git_add },
    diffRemoved   = { fg = p.git_del },
    diffChanged   = { fg = p.git_chg },
    diffFile      = { fg = p.peri },
    diffLine      = { fg = p.fg_dim },
    diffIndexLine = { fg = p.fg_dim },
    GitSignsAdd    = { fg = p.git_add },
    GitSignsChange = { fg = p.git_chg },
    GitSignsDelete = { fg = p.git_del },
    GitSignsAddNr    = { fg = p.git_add },
    GitSignsChangeNr = { fg = p.git_chg },
    GitSignsDeleteNr = { fg = p.git_del },
    GitSignsCurrentLineBlame = { fg = p.fg_subtle },

    -- DAP
    debugPC         = { bg = p.sel },
    debugBreakpoint = { fg = p.red },

    -- nvim-cmp
    CmpItemAbbr           = { fg = p.fg },
    CmpItemAbbrDeprecated = { fg = p.fg_dim, strikethrough = true },
    CmpItemAbbrMatch      = { fg = p.coral, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = p.coral, bold = true },
    CmpItemMenu           = { fg = p.fg_dim },
    CmpItemKind           = { fg = p.peri },
    CmpItemKindKeyword    = { fg = p.coral },
    CmpItemKindFunction   = { fg = p.peri },
    CmpItemKindMethod     = { fg = p.peri },
    CmpItemKindClass      = { fg = p.teal },
    CmpItemKindInterface  = { fg = p.teal },
    CmpItemKindStruct     = { fg = p.teal },
    CmpItemKindEnum       = { fg = p.teal },
    CmpItemKindConstant   = { fg = p.purple },
    CmpItemKindConstructor = { fg = p.purple },
    CmpItemKindSnippet    = { fg = p.amber },
    CmpItemKindText       = { fg = p.fg_dim },
    CmpItemKindVariable   = { fg = p.fg },
    CmpItemKindField      = { fg = p.fg },
    CmpItemKindProperty   = { fg = p.fg },

    -- Telescope
    TelescopeNormal         = { fg = p.fg, bg = p.surface_hi },
    TelescopeBorder         = { fg = p.peri, bg = p.surface_hi },
    TelescopeTitle          = { fg = p.coral, bold = true },
    TelescopePromptNormal   = { fg = p.fg, bg = p.surface },
    TelescopePromptBorder   = { fg = p.peri, bg = p.surface },
    TelescopePromptTitle    = { fg = p.coral, bold = true },
    TelescopePromptPrefix   = { fg = p.coral },
    TelescopePromptCounter  = { fg = p.fg_dim },
    TelescopePreviewTitle   = { fg = p.coral, bold = true },
    TelescopeResultsTitle   = { fg = p.coral, bold = true },
    TelescopeSelection      = { fg = p.fg, bg = p.sel_menu, bold = true },
    TelescopeSelectionCaret = { fg = p.coral, bg = p.sel_menu },
    TelescopeMatching       = { fg = p.coral, bold = true },
    TelescopeMultiSelection = { fg = p.peri },
    TelescopeResultsComment = { fg = p.fg_dim },

    -- nvim-tree
    NvimTreeNormal           = { fg = p.fg, bg = NONE },
    NvimTreeNormalNC         = { fg = p.fg, bg = NONE },
    NvimTreeWinSeparator     = { fg = p.surface },
    NvimTreeRootFolder       = { fg = p.coral, bold = true },
    NvimTreeFolderName       = { fg = p.peri },
    NvimTreeOpenedFolderName = { fg = p.peri, bold = true },
    NvimTreeEmptyFolderName  = { fg = p.fg_dim },
    NvimTreeFolderIcon       = { fg = p.coral },
    NvimTreeIndentMarker     = { fg = p.fg_subtle },
    NvimTreeSpecialFile      = { fg = p.amber },
    NvimTreeExecFile         = { fg = p.green },
    NvimTreeSymlink          = { fg = p.teal },
    NvimTreeImageFile        = { fg = p.purple },
    NvimTreeGitDirty         = { fg = p.git_chg },
    NvimTreeGitNew           = { fg = p.git_add },
    NvimTreeGitStaged        = { fg = p.git_add },
    NvimTreeGitDeleted       = { fg = p.git_del },
    NvimTreeGitRenamed       = { fg = p.peri },
    NvimTreeGitIgnored       = { fg = p.fg_subtle },
    NvimTreeCursorLine       = { bg = p.cursorline },
    NvimTreeWindowPicker     = { fg = p.inverse, bg = p.coral, bold = true },

    -- indent-blankline
    IblIndent     = { fg = p.indent },
    IblWhitespace = { fg = p.indent },
    IblScope      = { fg = p.fg_subtle },

    -- nvim-navic
    NavicText      = { fg = p.fg_dim },
    NavicSeparator = { fg = p.fg_subtle },

    -- nvim-notify
    NotifyBackground  = { bg = p.surface_hi },
    NotifyERRORBorder = { fg = p.red },
    NotifyWARNBorder  = { fg = p.amber },
    NotifyINFOBorder  = { fg = p.peri },
    NotifyDEBUGBorder = { fg = p.fg_dim },
    NotifyTRACEBorder = { fg = p.purple },
    NotifyERRORIcon   = { fg = p.red },
    NotifyWARNIcon    = { fg = p.amber },
    NotifyINFOIcon    = { fg = p.peri },
    NotifyDEBUGIcon   = { fg = p.fg_dim },
    NotifyTRACEIcon   = { fg = p.purple },
    NotifyERRORTitle  = { fg = p.red },
    NotifyWARNTitle   = { fg = p.amber },
    NotifyINFOTitle   = { fg = p.peri },
    NotifyDEBUGTitle  = { fg = p.fg_dim },
    NotifyTRACETitle  = { fg = p.purple },

    -- noice
    NoiceCmdlinePopup       = { fg = p.fg, bg = p.surface_hi },
    NoiceCmdlinePopupBorder = { fg = p.peri },
    NoiceCmdlineIcon        = { fg = p.coral },
    NoiceConfirmBorder      = { fg = p.peri },

    -- alpha (start screen)
    AlphaHeader   = { fg = p.coral },
    AlphaButtons  = { fg = p.peri },
    AlphaShortcut = { fg = p.amber },
    AlphaFooter   = { fg = p.fg_dim },
}

for name, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, name, spec)
end
